[package]
name = "bnpl_program"
version = "0.1.0"
edition = "2021"

[lib]
name = "bnpl_program"
crate-type = ["cdylib", "rlib"]

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"
serde = { version = "1.0", features = ["derive"] }